feat: Add support for pushing images to Alibaba Cloud ACR

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -458,6 +458,33 @@ jobs:
           tags: ${{ steps.digest.outputs.digest }}
           registry: ${{ env.PUSH_IMAGE_REGISTRY }}
 
+      - name: Push to Alibaba Cloud ACR
+        id: push_acr
+        run: |
+          ACR_REGISTRY="${{ secrets.ACR_REGISTRY }}"
+          ACR_NAMESPACE="${{ secrets.ACR_NAMESPACE }}"
+
+          IMAGE_NAME="${{ matrix.image_name }}"
+          IMAGE_TAG="${{ steps.generate-version.outputs.tag }}"
+
+          SOURCE_IMAGE="${{ steps.registry_case.outputs.lowercase }}/${IMAGE_NAME}:${IMAGE_TAG}"
+          TARGET_IMAGE="${ACR_REGISTRY}/${ACR_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG}"
+
+          echo "Attempting to log in to $ACR_REGISTRY"
+          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${ACR_REGISTRY} --username "${{ secrets.ACR_USERNAME }}" --password-stdin
+          echo "Login successful. Attempting to tag and push image."
+
+          if docker image inspect ${SOURCE_IMAGE} >/dev/null 2>&1; then
+            docker tag ${SOURCE_IMAGE} ${TARGET_IMAGE}
+            echo "Image tagged as ${TARGET_IMAGE}. Attempting to push."
+
+            docker push ${TARGET_IMAGE}
+            echo "Image pushed to ${TARGET_IMAGE}."
+          else
+            echo "Error: Source image ${SOURCE_IMAGE} not found locally. Cannot tag and push to ACR."
+            exit 1
+          fi
+
   generate_release:
     name: Generate Release
     needs: [push-ghcr]
